FROM oven/bun:1

WORKDIR /usr/src/app

RUN apt-get update -y && apt-get install -y openssl

COPY package.json bun.lock turbo.json ./

RUN bun install --verbose

COPY ./apps/frontend ./apps/frontend
COPY packages ./packages

EXPOSE 3000

CMD ["bun","run","start:fe"]

