FROM oven/bun:1

WORKDIR /usr/src/app
RUN apt-get update -y && apt-get install -y openssl

COPY package.json bun.lock turbo.json ./

RUN bun install

COPY ./apps/api ./apps/api
COPY packages ./packages

EXPOSE 3001

CMD ["sh", "-c", "bun run db:generate && bun run start:api"]
