FROM oven/bun:1
WORKDIR /usr/src/app
RUN apt-get update -y && apt-get install -y openssl
COPY package.json bun.lock turbo.json ./
RUN bun install
COPY ./apps/pusher ./apps/pusher
COPY packages ./packages
CMD ["bun","run","start:pusher"]