FROM oven/bun:1
WORKDIR /usr/src/app
RUN apt-get update -y && apt-get install -y openssl
COPY package.json bun.lock turbo.json ./

COPY packages/db/package.json packages/db/
COPY packages/redisstream/package.json packages/redisstream/
COPY apps/worker/package.json apps/worker/

RUN bun install
COPY . .
RUN bunx prisma generate --schema=packages/db/prisma/schema.prisma
CMD ["bun","run","start:worker"]