name: Deploy the Api
on:
  push:
    branches:
      [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Clone code
        uses: actions/checkout@v4

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PAT }}

      - name : Build and Push to dockerhub
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile.api
          push: true
          tags: |
            saumilbisht/buptime-api:${{ github.sha }}
            saumilbisht/buptime-api:latest

      - name: Update uptimeOps repo
        env:
          PAT: ${{secrets.PAT}}
        run: |
          git clone https://github.com/SaumilBisht/UptimeOps.git
          cd UptimeOps/api
          sed -i "s|image: saumilbisht/buptime-api:.*|image: saumilbisht/buptime-api:${{ github.sha }}|" manifest.yml
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add manifest.yml
          git commit -m "Update API image to ${{ github.sha }}"
          git push https://${PAT}@github.com/SaumilBisht/UptimeOps.git main
