name: Deploy the Frontend
on:
  push:
    branches:
      [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Clone code
        uses: actions/checkout@v4

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PAT }}
      - name : Build and Push to dockerhub
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile.fe
          push: true
          tags: saumilbisht/bUptime-fe:${{ github.sha }}
